<a href="https://colab.research.google.com/github/Asim347/Python_Tasks/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
print(pd.__version__)

2.2.2

In [4]:
A = pd.Series([2,3,4,5],index = ['a','b','c','d'])
A.values

array([2, 3, 4, 5])

In [5]:
type(A)

pandas.core.series.Series

In [7]:
A['a']

np.int64(2)

In [8]:
A['a' : 'c']

a    2
b    3
c    4
dtype: int64

In [9]:
grads_dict = {'a': 4, 'a-': 3.5, 'b': 3, 'b-' : 2.5, 'c' : 2}
grads = pd.Series(grads_dict)
grads.values

array([4. , 3.5, 3. , 2.5, 2. ])

In [10]:
grads.index

Index(['a', 'a-', 'b', 'b-', 'c'], dtype='object')

In [12]:
marks_dict = {'a': 87, 'a-': 80, 'b': 73, 'b-' : 68, 'c' : 60}
marks = pd.Series(marks_dict)
marks

a     87
a-    80
b     73
b-    68
c     60
dtype: int64

In [14]:
marks['a']

np.int64(87)

In [15]:
marks[0:2]

a     87
a-    80
dtype: int64

In [17]:
#Data frames
D = pd.DataFrame({'Marks':marks, "Grades": grads})
D
D.T

           a    a-     b    b-     c
Marks   87.0  80.0  73.0  68.0  60.0
Grades   4.0   3.5   3.0   2.5   2.0

In [18]:
D.values

array([[87. ,  4. ],
       [80. ,  3.5],
       [73. ,  3. ],
       [68. ,  2.5],
       [60. ,  2. ]])

In [19]:
D.values[3,1]

np.float64(2.5)

In [20]:
D.columns

Index(['Marks', 'Grades'], dtype='object')

In [25]:
D['ScaleMarks']  = 100*(D['Marks']/90)
D

    Marks  Grades  ScaleMarks
a      87     4.0   96.666667
a-     80     3.5   88.888889
b      73     3.0   81.111111
b-     68     2.5   75.555556
c      60     2.0   66.666667

In [30]:
D

    Marks  Grades
a      87     4.0
a-     80     3.5
b      73     3.0
b-     68     2.5
c      60     2.0

In [32]:
G = D[D['Marks']> 70]
G

    Marks  Grades
a      87     4.0
a-     80     3.5
b      73     3.0

In [33]:
A = pd.DataFrame([{'a':2, 'b':3}, {'b': 2, 'c':4}])
A

     a  b    c
0  2.0  3  NaN
1  NaN  2  4.0

In [41]:
A.fillna(0)

     a  b    c
0  2.0  3  0.0
1  0.0  2  4.0

In [46]:
data = pd.Series(['a','b','c'],index=[1,3,5])
data

1    a
3    b
5    c
dtype: object

In [47]:
data[1]

'a'

In [49]:
data[1:3]

3    b
5    c
dtype: object

In [50]:
data.loc[1:3]

1    a
3    b
dtype: object

In [51]:
data.iloc[1:3]

3    b
5    c
dtype: object

In [54]:
D.iloc[2,:]

Marks     73.0
Grades     3.0
Name: b, dtype: float64

In [59]:
from google.colab import files

uploaded = files.upload()  # This will open a file chooser

Saving 4. covid_19_data.csv to 4. covid_19_data.csv

In [61]:
import pandas as pd
from sklearn.impute import SimpleImputer

df = pd.read_csv('4. covid_19_data.csv')  # Use the uploaded filename

In [64]:
df.head(10)

        Date State               Region  Confirmed  Deaths  Recovered
0  4/29/2020   NaN          Afghanistan       1939      60        252
1  4/29/2020   NaN              Albania        766      30        455
2  4/29/2020   NaN              Algeria       3848     444       1702
3  4/29/2020   NaN              Andorra        743      42        423
4  4/29/2020   NaN               Angola         27       2          7
5  4/29/2020   NaN  Antigua and Barbuda         24       3         11
6  4/29/2020   NaN            Argentina       4285     214       1192
7  4/29/2020   NaN              Armenia       1932      30        900
8  4/29/2020   NaN              Austria      15402     580      12779
9  4/29/2020   NaN           Azerbaijan       1766      23       1267

In [68]:
df.drop(columns='State',inplace= True)

In [69]:
df.head()

        Date       Region  Confirmed  Deaths  Recovered
0  4/29/2020  Afghanistan       1939      60        252
1  4/29/2020      Albania        766      30        455
2  4/29/2020      Algeria       3848     444       1702
3  4/29/2020      Andorra        743      42        423
4  4/29/2020       Angola         27       2          7

In [73]:
df = df.rename(columns= {'Region' : 'Country'})

In [71]:
df['Date'] = pd.to_datetime(df['Date'])

In [72]:
df.head()

        Date       Region  Confirmed  Deaths  Recovered
0 2020-04-29  Afghanistan       1939      60        252
1 2020-04-29      Albania        766      30        455
2 2020-04-29      Algeria       3848     444       1702
3 2020-04-29      Andorra        743      42        423
4 2020-04-29       Angola         27       2          7

In [90]:
df2 = df.groupby('Country')[['Confirmed','Deaths','Recovered']].sum().reset_index()

In [91]:
df2

                Country  Confirmed  Deaths  Recovered
0           Afghanistan       1939      60        252
1               Albania        766      30        455
2               Algeria       3848     444       1702
3               Andorra        743      42        423
4                Angola         27       2          7
..                  ...        ...     ...        ...
182  West Bank and Gaza        344       2         71
183      Western Sahara          6       0          5
184               Yemen          6       0          1
185              Zambia         97       3         54
186            Zimbabwe         32       4          5

[187 rows x 4 columns]